
import { useState,type FormEvent } from 'react'
import { packs } from '../core/catalog'
import { mode,useWorkspace } from '../core/runtime'
import { Field,Icon,Modal } from '../components/ui'
export function CreateWorkspace({onClose,selectedPack='content'}:{onClose:()=>void;selectedPack?:string}){
 const {command,busy}=useWorkspace();const [name,setName]=useState(''),[pack,setPack]=useState(mode==='api'?'custom':selectedPack)
 async function submit(e:FormEvent){e.preventDefault();if(await command({type:'create-workspace',name,packId:pack}))onClose()}
 return <Modal title="A new space for your ideas" description="Choose a workforce pack. Agents, skills, and workflows come together in one workspace." onClose={onClose} wide><form onSubmit={submit} className="stack gap-5"><Field label="Workspace name"><input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. MESTHI Marketing" autoFocus/></Field><div className="pack-options">{packs.map(p=><button type="button" key={p.id} className={'pack-option '+(pack===p.id?'selected':'')} disabled={mode==='api'&&p.id!=='custom'} onClick={()=>setPack(p.id)}><Icon name={p.icon} size={25}/><strong>{p.name}</strong><small>{p.agents.length?p.agents.length+' agents · '+p.skills.length+' skills':'Start with a blank canvas'}</small>{pack===p.id&&<Icon name="Check" className="pack-check"/>}</button>)}</div><p className="inline-note"><Icon name="ShieldCheck"/>{mode==='demo'?'Creates a local demo workspace. Public actions are simulated only.':'C4 creates an empty workspace. Packs require a backend extension.'}</p><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button disabled={busy} className="button primary">Create workspace<Icon name="ArrowRight"/></button></div></form></Modal>
}
export function CreateRun({onClose,workflowId='',initialTitle='',initialBrief=''}:{onClose:()=>void;workflowId?:string;initialTitle?:string;initialBrief?:string}){
 const {activeId,workflows,agents,command,busy}=useWorkspace()
 const available=mode==='api'?[{id:'c4-task',name:'C4 task',enabled:true}]:workflows.filter(w=>w.enabled)
 const [title,setTitle]=useState(initialTitle),[brief,setBrief]=useState(initialBrief),[flowId,setFlowId]=useState(workflowId||available[0]?.id||''),[agentId,setAgentId]=useState(agents[0]?.id||'')
 const flow=workflows.find(w=>w.id===flowId)
 async function submit(e:FormEvent){e.preventDefault();if(await command({type:'create-run',workspaceId:activeId,title,brief,workflowId:flowId,agentId}))onClose()}
 return <Modal title="Give your team a mission" description="Describe the outcome. Your workflow takes care of the steps." onClose={onClose}><form onSubmit={submit} className="stack gap-4"><Field label="Task name"><input required maxLength={140} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Create our September launch campaign" autoFocus/></Field><Field label="Brief"><textarea required rows={4} maxLength={10000} value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Include the audience, tone, and desired outcome."/></Field><div className="form-grid"><Field label="Workflow"><select required value={flowId} onChange={e=>setFlowId(e.target.value)}>{!available.length&&<option value="">No enabled workflows</option>}{available.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field><Field label="Lead agent"><select required value={agentId} onChange={e=>setAgentId(e.target.value)}>{!agents.length&&<option value="">Create an agent first</option>}{agents.map(a=><option key={a.id} value={a.id}>{a.name+' · '+a.role}</option>)}</select></Field></div>{flow&&<div className="run-estimate"><span><Icon name="Coins"/>Estimated {flow.estimatedCredits} credits</span><span><Icon name="ShieldCheck"/>{flow.requiresApproval?'Human approval':'Draft output'}</span></div>}<p className="inline-note">{mode==='demo'?'Demo runs create sample text. They do not call AI, render media, or publish.':'Creates a backend Task. Queue and start are separate actions in task details.'}</p><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button disabled={busy||!agents.length||!available.length} className="button primary"><Icon name="Play" size={15}/>{mode==='demo'?'Start demo run':'Create task'}</button></div></form></Modal>
}
