import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test.beforeEach(async({page})=>{
  page.on('pageerror',error=>console.log('Browser exception:',error.message))
  page.on('console',message=>{if(message.type()==='error')console.log('Browser console:',message.text())})
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  await expect(page.locator('canvas, .fatal-error, .office-fallback')).toBeVisible()
  await expect(page.locator('.fatal-error')).toHaveCount(0)
})
test('mission control and Phaser render without runtime errors',async({page})=>{
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.reload()
  await expect(page.getByRole('heading',{name:'Mission control.'})).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  await expect(page.locator('.metric')).toHaveCount(4)
  for(const metric of await page.locator('.metric').all())await expect(metric).toBeVisible()
  await mkdir('docs/screenshots',{recursive:true})
  await page.screenshot({path:'docs/screenshots/mission-control.png',fullPage:true})
  await page.getByRole('button',{name:'Open full live office'}).click()
  await expect(page.getByRole('heading',{name:'The live office.'})).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  await page.screenshot({path:'docs/screenshots/live-office.png',fullPage:true})
  await page.getByRole('button',{name:'Whiteboard',exact:false}).click()
  await expect(page.getByRole('heading',{name:'Workflows.'})).toBeVisible()
  expect(errors).toEqual([])
})
test('workspace onboarding, task lifecycle, and saved documents stay isolated',async({page})=>{
  await page.getByRole('button',{name:'Create workspace',exact:true}).click()
  const create=page.getByRole('dialog')
  await create.getByLabel('Workspace name').fill('Launch Lab')
  await create.getByRole('button',{name:/Research Team/}).click()
  await create.getByRole('button',{name:'Create workspace',exact:true}).click()
  await expect(create).not.toBeVisible()
  await expect(page.getByLabel('Switch workspace')).toHaveValue(/ws-/)
  await expect(page.getByLabel('Switch workspace').locator('option:checked')).toHaveText('Launch Lab')
  await expect(page.getByRole('button',{name:/September brand launch/})).toHaveCount(0)
  await page.getByRole('button',{name:'New task',exact:true}).click()
  let dialog=page.getByRole('dialog')
  await dialog.getByLabel('Task name').fill('Launch audience research')
  await dialog.getByLabel('Brief',{exact:true}).fill('Prepare a concise research outline for a creator audience.')
  await dialog.getByRole('button',{name:'Start demo run'}).click()
  await expect(dialog).not.toBeVisible()
  await page.locator('.task-title').filter({hasText:'Launch audience research'}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByRole('button',{name:'Pause',exact:true}).click()
  await expect(dialog.locator('.status')).toHaveText('Paused')
  await dialog.getByRole('button',{name:'Resume',exact:true}).click()
  await expect(dialog.locator('.status')).toHaveText('In progress')
  await dialog.getByRole('button',{name:'Cancel run',exact:true}).click()
  await expect(dialog.locator('.status')).toHaveText('Cancelled')
  await dialog.getByRole('button',{name:'Close',exact:true}).click()
  await page.getByRole('navigation').getByRole('button',{name:'Knowledge & skills'}).click()
  await page.getByRole('button',{name:'Add document'}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByLabel('Document title').fill('Launch positioning')
  await dialog.getByLabel('Content',{exact:true}).fill('# Launch\n\nA private brief for Launch Lab.')
  await dialog.getByRole('button',{name:'Save document'}).click()
  await page.reload()
  await page.getByLabel('Switch workspace').selectOption({label:'Launch Lab'})
  await page.getByRole('navigation').getByRole('button',{name:'Knowledge & skills'}).click()
  await page.getByRole('button',{name:/Launch positioning/}).click()
  await expect(page.locator('.document-preview')).toContainText('A private brief for Launch Lab.')
  const downloaded=page.waitForEvent('download')
  await page.getByRole('dialog').getByRole('button',{name:'Download',exact:true}).click()
  expect((await downloaded).suggestedFilename()).toBe('Launch positioning.md')
  await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click()
  await page.getByLabel('Switch workspace').selectOption({label:'MESTHI Creative'})
  await page.getByRole('navigation').getByRole('button',{name:'Knowledge & skills'}).click()
  await expect(page.getByRole('button',{name:/Launch positioning/})).toHaveCount(0)
  await expect(page.getByRole('button',{name:/Brand foundations/})).toBeVisible()
})
test('mobile navigation, theme, and reduced motion remain usable',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('navigation').getByRole('button',{name:'Content studio'}).click()
  await expect(page.getByRole('heading',{name:'Content studio.'})).toBeVisible()
  await expect(page.locator('.sidebar')).not.toHaveClass(/open/)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
  await mkdir('docs/screenshots',{recursive:true})
  await page.screenshot({path:'docs/screenshots/mobile-content.png',fullPage:true})
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('navigation').getByRole('button',{name:'Settings',exact:true}).click()
  const toggle=page.getByRole('button',{name:/Switch to dark/i})
  if(await toggle.count())await toggle.click()
  else await page.getByRole('button',{name:'Toggle color theme'}).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
})
test('GSAP entry animation settles and keyboard dialog navigation works',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'})
  await page.reload()
  await expect(page.locator('.page-heading h1')).toBeVisible()
  await expect(page.locator('.metric').first()).toHaveCSS('opacity','1')
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByLabel('Global search').fill('Workforce packs')
  await page.getByRole('dialog').getByRole('button',{name:/Workforce packs/}).click()
  await expect(page.getByRole('heading',{name:'Workforce packs.'})).toBeVisible()
  await expect(page.locator('.template-card').first()).toHaveCSS('opacity','1')
  await page.getByRole('button',{name:'Create workspace',exact:true}).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})
