export const agentColors = ['#b5c99a', '#a9c5db', '#dfc18f', '#c1b1d5', '#e0b0a7']
export const packs = [
  {
    id: 'content',
    name: 'Content Studio',
    icon: 'Clapperboard',
    color: '#b5c99a',
    description: 'Research, write, storyboard, and prepare content for review.',
    skills: [
      'trend-research',
      'audience-research',
      'copywriting',
      'hook-writing',
      'storytelling',
      'storyboard',
      'image-prompting',
      'video-prompting',
      'caption-writing',
      'SEO',
      'hashtag-research',
      'content-analysis',
    ],
    agents: [
      ['Nova', 'Content Strategist'],
      ['Atlas', 'Research Agent'],
      ['Quill', 'Script Writer'],
      ['Mira', 'Creative Director'],
      ['Echo', 'Publisher'],
    ],
    workflows: [
      {
        name: 'Short-form video',
        description: 'Turn a brief into a script, storyboard, and publishing draft.',
        steps: ['Research', 'Script', 'Storyboard', 'Video draft', 'Approval', 'Publish'],
        requiresApproval: true,
        estimatedCredits: 80,
      },
      {
        name: 'Social image post',
        description: 'Create a researched caption and an image brief.',
        steps: ['Research', 'Copy', 'Image brief', 'Approval'],
        requiresApproval: true,
        estimatedCredits: 30,
      },
      {
        name: 'Campaign strategy',
        description: 'Build a campaign plan with a clear audience and message.',
        steps: ['Audience', 'Research', 'Strategy', 'Report'],
        requiresApproval: false,
        estimatedCredits: 25,
      },
      {
        name: 'Performance report',
        description: 'Review supplied performance and document insights.',
        steps: ['Collect', 'Analyze', 'Report'],
        requiresApproval: false,
        estimatedCredits: 15,
      },
    ],
  },
  {
    id: 'software',
    name: 'Software Team',
    icon: 'Code2',
    color: '#a9c5db',
    description: 'A coordinated engineering team, from architecture to pull request.',
    skills: ['system-design', 'java', 'react', 'testing', 'docker', 'kubernetes'],
    agents: [
      ['Archi', 'Architect'],
      ['Byte', 'Backend Engineer'],
      ['Pixel', 'Frontend Engineer'],
      ['Scout', 'QA Engineer'],
      ['Ship', 'DevOps Engineer'],
    ],
    workflows: [
      {
        name: 'Issue to pull request',
        description: 'Plan an issue, implement it, test, and request review.',
        steps: ['Plan', 'Code', 'Test', 'Pull request', 'Approval'],
        requiresApproval: true,
        estimatedCredits: 45,
      },
      {
        name: 'Architecture review',
        description: 'Evaluate system boundaries and document decisions.',
        steps: ['Context', 'Analyze', 'Review', 'Report'],
        requiresApproval: false,
        estimatedCredits: 25,
      },
    ],
  },
  {
    id: 'research',
    name: 'Research Team',
    icon: 'Telescope',
    color: '#d1bbd9',
    description: 'Investigate a question, validate sources, and deliver a clear report.',
    skills: ['web-research', 'source-validation', 'analysis', 'reporting'],
    agents: [
      ['Atlas', 'Researcher'],
      ['Vera', 'Fact Checker'],
      ['Sage', 'Analyst'],
      ['Scribe', 'Report Writer'],
    ],
    workflows: [
      {
        name: 'Research report',
        description: 'Explore a question with evidence and concise synthesis.',
        steps: ['Research', 'Cross-check', 'Analyze', 'Report'],
        requiresApproval: false,
        estimatedCredits: 20,
      },
      {
        name: 'Competitor monitor',
        description: 'Prepare a competitor review and notification draft.',
        steps: ['Observe', 'Compare', 'Analyze', 'Approval'],
        requiresApproval: true,
        estimatedCredits: 25,
      },
    ],
  },
  {
    id: 'custom',
    name: 'Build your own',
    icon: 'Sparkles',
    color: '#dfcfaa',
    description: 'Start with an empty workspace and configure your own agents.',
    skills: [] as string[],
    agents: [] as string[][],
    workflows: [],
  },
]
export const toolsCatalog = [
  {
    id: 'web',
    name: 'Web Search',
    category: 'Research',
    icon: 'Globe',
    description: 'Discover sources and gather context.',
    transport: 'Native API',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Development',
    icon: 'GitBranch',
    description: 'Repositories, issues, and pull requests.',
    transport: 'MCP / OAuth',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'Publishing',
    icon: 'Image',
    description: 'Prepare and publish reviewed content.',
    transport: 'OAuth adapter',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: 'Publishing',
    icon: 'Music2',
    description: 'Share short videos with your audience.',
    transport: 'OAuth adapter',
  },
  {
    id: 'x',
    name: 'X',
    category: 'Publishing',
    icon: 'MessageCircle',
    description: 'Post updates and follow conversations.',
    transport: 'OAuth adapter',
  },
  {
    id: 'image',
    name: 'Image generation',
    category: 'Creative',
    icon: 'Image',
    description: 'Generate imagery from creative briefs.',
    transport: 'Provider API',
  },
  {
    id: 'video',
    name: 'Video generation',
    category: 'Creative',
    icon: 'Film',
    description: 'Render storyboard scenes into video.',
    transport: 'Provider API',
  },
  {
    id: 'mcp',
    name: 'Custom MCP',
    category: 'Tools',
    icon: 'Plug',
    description: 'Extend your workforce with scoped tools.',
    transport: 'MCP gateway',
  },
]
